// No Letters B, F, Q, U, W, X, Y, Z
var noLettersBibleBooks = ["B", "F", "Q", "U", "W", "V", "X", "Y", "Z"]


var bibleBooks = [
    "Acts",
    "Amos",
    "1 Chronicles",
    "2 Chronicles",
    "1Chronicles",
    "2Chronicles",
    "Colossians",
    "1 Corinthians",
    "2 Corinthians",
    "1Corinthians",
    "2Corinthians",
    "Daniel",
    "Deuteronomy",
    "Ecclesiastes",
    "Ephesians",
    "Esther",
    "Exodus",
    "Ezekiel",
    "Ezra",
    "Galatians",
    "Genesis",
    "Habakkuk",
    "Haggai",
    "Hebrews",
    "Hosea",
    "Isaiah",
    "James",
    "Jeremiah",
    "Job",
    "Joel",
    "John",
    "1 John",
    "2 John",
    "3 John",
    "1John",
    "2John",
    "3John",
    "Jonah",
    "Joshua",
    "Jude",
    "Judges",
    "1 Kings",
    "2 Kings",
    "1Kings",
    "2Kings",
    "Lamentations",
    "Leviticus",
    "Luke",
    "Malachi",
    "Mark",
    "Matthew",
    "Micah",
    "Nahum",
    "Nehemiah",
    "Numbers",
    "Obadiah",
    "1 Peter",
    "2 Peter",
    "1Peter",
    "2Peter",
    "Philemon",
    "Philippians",
    "Proverbs",
    "Psalms",
    "Revelation",
    "Romans",
    "Ruth",
    "1 Samuel",
    "2 Samuel",
    "1Samuel",
    "2Samuel",
    "Song Of Solomon",
    "1 Thessalonians",
    "2 Thessalonians",
    "1Thessalonians",
    "2Thessalonians",
    "1 Timothy",
    "2 Timothy",
    "1Timothy",
    "2Timothy",
    "Titus",
    "Zechariah",
    "Zephaniah",
]